/*
 * SCI_ACCEL.h
 *
 *  Created on: April 29, 2020
 *      Author: Le Truong Thanh
 *      Purpose: Software Command Interface for ACCELEROMETER MMA8652
 *      Comment: DO NOT EDIT THIS FILE
 *      First version for ORANGE DEV BOARD (RAK4200)
 */

#ifndef SRC_SCI_ACCEL_H_
#define SRC_SCI_ACCEL_H_

#include <stdbool.h>
#include <stdint.h>
#include "HCI_ACCEL.h"

/*****************************************************************************************************************/
/*													MACROS DEFINITION											 */
/*****************************************************************************************************************/
#define SENSIBILITY_DEFAULT		20

/*****************************************************************************************************************/
/*													   DATA-STRUCTS												 */
/*****************************************************************************************************************/
typedef struct
{
  float X_F16;
  float Y_F16;
  float Z_F16;
} AxisDef;

typedef enum
{
	LOW_POWER =0,
	HIGH_RESOLUTION
}ResolutionMode;

typedef struct
{
	uint8_t GSEL1;
	uint8_t GSEL0;
	uint8_t EN16G;
	uint8_t gravity;
}AccelRange_t;

typedef enum
{
	G2 =0,
	G4,
	G8,
	G8_14bit,
	G16_1,
	G16_2,
	G16_3,
	G16_14bit
}AccelRange_e;

typedef struct
{
	uint8_t OWUFA;
	uint8_t OWUFB;
	uint8_t OWUFC;
}DataRateWKUP_t;

typedef enum
{
	DR0_781=0,
	DR1_536,
	DR3_125,
	DR6_25,
	DR12_5,
	DR25,
	DR50,
	DR100
}DataRateWKUP_e;

typedef enum
{
	POLARITY_LOW=0,
	POLARITY_HIGH
}Polarity_e;

typedef enum
{
	LATCH=0,
	PULSE
}INTResType_e;

typedef enum
{
	MODE_DISABLE=0,
	MODE_ENABLE
}Mode_e;

typedef struct
{
	uint8_t OSAA;
	uint8_t OSAB;
	uint8_t OSAC;
	uint8_t	OSAD;
}DataRateLPF_t;

typedef enum
{
	DR0_781__LPF0_3905=0,
	DR1_563__LPF0_781,
	DR3_125__LPF1_563,
	DR6_25__LPF3_125,
	DR12_5__LPF6_25,
	DR25__LPF12_5,
	DR50__LPF25,
	DR100__LPF50,
	DR200__LPF100,
	DR400__LPF200,
	DR800__LPF400,
	DR1600__LPF800
}DataRateLPF_e;


typedef enum
{
	Sens_14bit=2,
	Sens_12bit=4,
	Sens_8bit=8
}SensResolution_e;

typedef struct
{
	SensResolution_e resolution;
	uint8_t gravity_range;
	uint16_t count_per_g;
}SensInfomation_t;

typedef enum
{
	BIT14_G8=0,
	BIT14_G16,
	BIT12_G2,
	BIT12_G4,
	BIT12_G8,
	BIT12_G16_1,
	BIT12_G16_2,
	BIT12_G16_3,
	BIT8_G2,
	BIT8_G4,
	BIT8_G8,
	BIT8_G16_1,
	BIT8_G16_2,
	BIT8_G16_3
}SensMode_e;

/*****************************************************************************************************************/
/*											    Software Command Interface     									 */
/*****************************************************************************************************************/
typedef struct{
	/*
	 * Axis information
	 */
	AxisDef Axis_T;

	uint8_t sensibility;

	uint8_t INT_FLAG;

	const uint16_t EXTI_PIN;

	SensMode_e Mode;

	const void (*HCI_ACCEL_I2C_INIT)(void);

	const void (*HCI_ACCEL_I2C_DEINIT)(void);

	const void (*HCI_ACCEL_I2C_WRITE)(uint16_t adr, uint16_t value);

	const void (*HCI_ACCEL_I2C_READ)(uint16_t adr, uint8_t *buffer, uint16_t length);

	const uint8_t (*HCI_ACCEL_I2C_CHECK)(uint16_t adr);

	const void (*HCI_ACCEL_GPIO_INIT)(void);

	const void (*HCI_ACCEL_DELAYMS)(uint32_t ms);

	const void (*SCI_ACCEL_INIT)(void);

	const void (*SCI_ACCEL_ACTIVE)(void);

	const void (*SCI_ACCEL_STANDBY)(void);

	const void (*SCI_ACCEL_RESET)(void);

	const void (*SCI_ACCEL_READXYZ)(void);

	const void (*SCI_ACCEL_SLEEP)(void);

	const void (*SCI_ACCEL_MAINCONFIG)(void);

	const void (*SCI_ACCEL_EXTI_CALLBACK)(void);

	const void (*SCI_ACCEL_SETMODE)(SensMode_e mode);

	const void (*SCI_ACCEL_ENABLE_NEW_ACCEL_INT)(void);

	const void (*SCI_ACCEL_DISABLE_NEW_ACCEL_INT)(void);

	const void (*SCI_ACCEL_ENABLEWKUP)(void);

	const void (*SCI_ACCEL_DISABLEWKUP)(void);

	const void (*SCI_ACCEL_SET_DATARATE_WKUP)(DataRateWKUP_e rating);

	const void (*SCI_ACCEL_ENBALE_PHYINT)(void);

	const void (*SCI_ACCEL_DISABLEPHYINT)(void);

	const void (*SCI_ACCEL_SET_POLARITY)(Polarity_e pol);

	const void (*SCI_ACCEL_SET_INT_RES_TYPE)(INTResType_e type);

	const void (*SCI_ACCEL_SET_UNLATCH_MODE)(Mode_e mode);

	const void (*SCI_ACCEL_SET_AXIS_INT_TYPE)(Mode_e xneg,Mode_e xpos,Mode_e yneg,Mode_e ypos,Mode_e zneg,Mode_e zpos);

	const void (*SCI_ACCEL_SET_DATARATE_LPF)(DataRateLPF_e rating);

	const void (*SCI_ACCEL_SET_WKUP_COUNTER)(uint8_t counter);

	const void (*SCI_ACCEL_SET_NA_COUNTER)(uint8_t counter);

	const void (*SCI_ACCEL_SET_WKUP_THRESHOLD)(float gravity_threshold);

}AccelerationSensorExt;

extern AccelerationSensorExt Accel;
#endif /*SRC_SCI_ACCEL_H_*/
